import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {MatToolbarModule} from '@angular/material/toolbar';
import { MatNativeDateModule,
   MatInputModule,
    MatDatepickerModule,
     MatSlideToggleModule,
     MatRadioModule,
     MatSelectModule,
     MatFormFieldModule,
     MatButtonModule,
     MatSnackBarModule,
     MatTableModule,
     MatIconModule,
     MatPaginatorModule,
     MatSortModule,
     MatDialogModule,
     MatCardModule,
     MatTabsModule,
     MatProgressBarModule,
     MatBadgeModule,
     MatAutocompleteModule,
     MatChipsModule,
     } from '@angular/material';
import {MatGridListModule} from '@angular/material/grid-list';


@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatToolbarModule,
    MatGridListModule,
    MatFormFieldModule,
    MatRadioModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSelectModule,
    MatButtonModule,
    MatSnackBarModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatIconModule,
    MatDialogModule,
    MatCardModule,
    MatTabsModule,
    MatProgressBarModule,
    MatBadgeModule,
    MatAutocompleteModule,
    MatChipsModule,

  ],
  exports : [
    MatToolbarModule,
    MatSlideToggleModule,
    MatFormFieldModule,
    MatGridListModule,
    MatRadioModule,
    MatInputModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatSelectModule,
    MatButtonModule,
    MatSnackBarModule,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
    MatIconModule,
    MatDialogModule,
    MatCardModule,
    MatTabsModule,
    MatProgressBarModule,
    MatBadgeModule,
    MatAutocompleteModule,
    MatChipsModule,
  ]
})
export class MaterialModule { }
